name: d

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout your pull request code
     
- uses: MarketingPipeline/Screenshot-Github-Action@main # You can change this to use a specific version.
  with:
    # The arguments for the `git add` command (see the paragraph below for more info)
    # Default: '.'
    Files: "https://github.com"

    # The name of the user that will be displayed as the author of the commit.
    # Default: depends on the default_author input
    Directory_To_Get_HTML_File: ""

    # The email of the user that will be displayed as the author of the commit.
    # Default: depends on the default_author input
    Directory_To_Save_HTML_File: "URL"
