name: ds

on: workflow_dispatch

jobs:
  bssuild:
    runs-on: ubuntu-latest
    steps:
      # Checkout your pull request code
    - name: Hello 
    - uses: MarketingPipeline/Screenshot-Github-Action@main # You can change this to use a specific version.
      with:
       # The arguments for the `git add` command (see the paragraph below for more info)
    # Default: '.'
         Files: "https://github.com"
         Directory_To_Get_HTML_File: ""
         Directory_To_Save_HTML_File: "URL"
         run: python screenshotter.py

   
