name: Reusable workflow example

on:
  workflow_dispatch:
    inputs:
      Files:
        description: 'URL(s) or File(s) to take screenshot of (seperate by comma):'
        required: true
        type: string
        default: "https://github.com,"  
      Directory_To_Get_HTML_File:
        description: 'The directory name to save screenshots to (example : path/to/directory'
        required: false
        type: string
        default: "./"          
      Directory_To_Save_HTML_File:
        description: 'URL or File'
        required: True
        type: string
        default: 'URL'
        


jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
     - uses: lsetiawan/py-github-actions-starter@v1
       with:
         time: '5'   
    
