name: Take a Screenshot

on:
   workflow_dispatch:
     inputs:
       Files:
         description: 'URL(s) or File(s) to take screenshot of (seperate by comma):'
         required: true
         default: "https://github.com,"
       

       Directory_To_Get_HTML_File:
         description: 'The directory name to save screenshots to (example : path/to/directory'
         required: False
         default: ''

       Directory_To_Save_HTML_File:
        description: 'URL or File'
        required: True
        default: 'URL'



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Take a Screenshot
        uses: MarketingPipeline/Screenshot-Github-Action@main
 
          # Optional, the action will create a new branch and
          # upload the screenshots to that branch.
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.9'
      - name: Installed package list
        run: apt list --installed
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
            
      - name: Install all necessary packages
        run: pip install requests beautifulsoup4 pandas chromedriver-autoinstaller selenium pyvirtualdisplay 
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Run the scraping script
        working-directory: ./
        run: |
         INPUT_STORE=${{ github.event.inputs.Files }} INPUT_STORE2=${{ github.event.inputs.Directory_To_Get_HTML_File }} INPUT_STORE3=${{ github.event.inputs.Directory_To_Save_HTML_File }}  INPUT_STORE4=${{ github.event.repository.name }} python screenshotter.py  
        
        
   


      - name: Commit and Push
        run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git commit -m "Screenshot added"
         git push
