name: Puppeteer Screenshot Action
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Take photo of github.com
      uses: "lannonbr/puppeteer-screenshot-action@1.0.0"
      with:
          url: https://github.com





