name: Comment Webpage Screenshot

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout your pull request code
      - uses: actions/checkout@v2

      # Run Screenshot Comment Action
      - name: Run Screenshot Comment Action
        uses: MarketingPip/comment-webpage-screenshot@main
        with:
          upload_to: imgur
          # Capture Screenshots of Changed HTML Files
          capture_changed_html_files: yes
          # Comma seperated paths to any other HTML File
          capture_html_file_paths: "/pages/index.html"
          
    
